dist: trusty
sudo: required

env:
  - TERRAFORM_VERSION=0.11.7

install:
  - curl -Os https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
  - curl -Os https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_SHA256SUMS
  - curl -Os https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_SHA256SUMS.sig
  - gpg --import hashicorp.asc
  - gpg --verify terraform_${TERRAFORM_VERSION}_SHA256SUMS.sig terraform_${TERRAFORM_VERSION}_SHA256SUMS
  - shasum -a 256 -c terraform_${TERRAFORM_VERSION}_SHA256SUMS 2> /dev/null | grep terraform_${TERRAFORM_VERSION}_linux_amd64.zip | grep OK
  - sudo unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip -d /usr/local/bin
  - sudo chmod 755 /usr/local/bin/terraform

before_script:
  - echo "access_key  = \"$AWS_ACCESS_KEY\""   >  terraform/terraform.tfvars
  - echo "secret_key  = \"$AWS_SECRET_KEY\""   >> terraform/terraform.tfvars
  - echo "region      = \"$AWS_REGION\""       >> terraform/terraform.tfvars
  - echo "environment = \"$AWS_ENVIRONMENT\""  >> terraform/terraform.tfvars

script:
  - make keys
  - make init plan
