name: Main
on: push
jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Configure Terraform
        shell: bash
        working-directory: ./terraform
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
        run: |
          echo "access_key  = \"$AWS_ACCESS_KEY\"" > terraform.tfvars
          echo "secret_key  = \"$AWS_SECRET_KEY\"" >> terraform.tfvars
          echo 'region      = "us-east-1"'         >> terraform.tfvars
          echo 'environment = "test"'              >> terraform.tfvars
      - name: Validate Terraform
        run: make keys init validate
